### ISSUE TITLE
Где скачать архив плагина?

### ISSUE THREAD

**Issue by svidpro** [POSIdev-community/AI.Plugin.IntelliJ#1]
Приветсвую!

Думаю где-то нарушена пользовательская цепочка по распространению плагина :)
Либо я что-то прослушал.
Побывал на конференции, перешел в репозиторий по ссылке с qr-code.

В инструкции есть пункты: 
2.Click the gear icon and select Install Plugin from Disk.
3. Specify the path to the plugin ZIP archive.

Вопрос где взять архив плагина?

Аналогичная история и в [AI.Plugin.VSCode](https://github.com/POSIdev-community/AI.Plugin.VSCode)
Install from VSIX
Где взять VSIX?

**Comment by vldF** [comment]
Здравствуйте! Обратите внимание на вкладку releases на главной странице каждого из плагинов 

Для IntelliJ  https://github.com/POSIdev-community/AI.Plugin.IntelliJ/releases
Для Visual Studio Code https://github.com/POSIdev-community/AI.Plugin.VSCode/releases

Удачного использования и ждем обратной связи

**Comment by svidpro** [comment]
Спасибо, не заметил.
