### ISSUE TITLE
Нет возможности скачать code analyzer за корпоративным proxy

### ISSUE THREAD

**Issue by LimeBeck** [POSIdev-community/AI.Plugin.IntelliJ#3]
При попытке скачать code analyzer за корпоративным прокси сразу выдаёт "В соединении отказано". На настройки прокси в IDEA не реагирует. Также нигде не смог найти ссылку на анализатор, чтобы скачать вручную через браузер.

**Comment by alyadusov** [comment]
Прямые ссылки для версии 2.1.0 вот:

windows: https://update.ptsecurity.com/api/v6/products/AI.INFRASTRUCTURE.INSTALLATOR.zip/2.1.0.29976/download/AI.INFRASTRUCTURE.INSTALLATOR.2.1.0.29976.zip

linux: https://update.ptsecurity.com/api/v6/products/AI.INFRASTRUCTURE.INSTALLATOR.tar.gz/2.1.0.29976/download/AI.INFRASTRUCTURE.INSTALLATOR.2.1.0.29976.tar.gz

osx: https://update.ptsecurity.com/api/v6/products/AI.INFRASTRUCTURE.INSTALLATOR.pkg/2.1.0.29976/download/AI.INFRASTRUCTURE.INSTALLATOR.2.1.0.29976.pkg

А сами папки куда класть - описаны в readme. (Для osx инсталятор сделает это сам)
